version: '2'
services:
    netss-campaign-app:
        image: netss
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://netss-campaign-postgresql:5432/netss_campaign
            - SPRING_RABBIT_HOST=netss-campaign-abbit:5672
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        depends_on:
            - netss-campaign-postgresql
            - netss-campaign-rabbit
    netss-campaign-postgresql:
        extends:
            file: postgresql.yml
            service: netss-campaign-postgresql
    netss-campaign-rabbit:
        extends:
            file: rabbitmq.yml
            service: rabbit-campaign

